#!/bin/bash
#
# yakuake-session - A script to create new Yakuake sessions from command-line.
#
# Copyright 2010-2017 Jesús Torres <jmtorres@ull.es>
#
# yakuake-session comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
# This is free software, and you are welcome to redistribute it
# under certain conditions; see COPYING for details.
#

### Utility functions
# A few utility functions to show errors, handle programa exit and more

PROGRAM_NAME="$(basename "$0")"
SESSION_FILE=''

# Show information about how to use this program
function show_help() {
	cat <<-EOF

	Usage: $PROGRAM_NAME [options] [args]

	Options:
	  --help                    Show help about options.
	  -h, --homedir             Set the working directory of the new tab to the user's home.
	  -w, --workdir <dir>       Set the working directory of the new tab to 'dir'
	  --hold, --noclose         Do not close the session automatically when the command ends.
	  -p <property=value>       Change the value of a profile property (only for KDE 4).
	  -q                        Do not open yakuake window.
	  -t <title>                Set the title of the new tab
	  -e <cmd>                  Command to execute. This option will catch all following arguments, so use it as the last option.

	Arguments:
	  args                      Arguments passed to command (for use with -e).
	EOF
}

# Functions to show error and warning messages
if type -P kdialog &> /dev/null; then

	function error_exit() {
		kdialog ${WINDOWID:+--attach $WINDOWID} \
			--title "$PROGRAM_NAME error" \
			--error "$PROGRAM_NAME error: ${2:-'unknown error'}."
		exit "${1:-1}"
	}

	function warning() {
		kdialog ${WINDOWID:+--attach $WINDOWID} \
			--title "$PROGRAM_NAME warning" \
			--sorry "$PROGRAM_NAME warning: ${1:-'unknown error'}"
}

else

	function error_exit() {
		echo "$PROGRAM_NAME: error: ${2:-'unknown error'}" 1>&2
		exit "${1:-1}"
	}

	function warning() {
		echo "$PROGRAM_NAME: warning: ${1:-'unknown error'}" 1>&2
	}

fi

### Profile setup
# Functions to handle terminal profile properties and setup
# them in the new session.

profile_properties=''

function add_profile_setting() {
	if [[ -z "$profile_properties" ]]; then
		profile_properties="$1"
	else
		profile_properties="$profile_properties;$1"
	fi
}

function profile_setup_command() {
	type -P konsoleprofile &> /dev/null || echo 'true'
	if [[ -n "$profile_properties" ]]; then
		echo "konsoleprofile '$profile_properties'"
	else
		echo 'true'
	fi
}

### Yakuake IPC
# Functions to make it easy to invoke some Yakuake methods

# Detect which IPC technology we have to use to talk to Yakuake
function detect_ipc_interface() {
	type -P qdbus &> /dev/null && \
		qdbus 2> /dev/null | grep -q org.kde.yakuake
	if [[ "$?" == 0 ]]; then
		echo dbus
		return
	fi
	type -P dcop &> /dev/null && \
		dcop 2> /dev/null | grep -q yakuake
	if [[ "$?" == 0 ]]; then
		echo dcop
		return
	fi
	echo none
}

# Initialize IPC interface to Yakuake
function init_ipc_interface() {
	local comm=$(detect_ipc_interface)
	if [[ "$comm" == none ]]; then

		# Maybe Yakuake is not running. Launch de program and try it again
		type -P yakuake &> /dev/null ||
			error_exit 20 "Yakuake is not installed"
		yakuake &> /dev/null ||
			error_exit 126 "Yakuake can not be executed: exit with status $?"
		comm=$(detect_ipc_interface)
	fi

	if [[ "$comm" == dbus ]]; then
		type -P wmctrl &> /dev/null ||
			error_exit 21 "wmctrl is not installed"

		function yakuake_addsession() {
			qdbus org.kde.yakuake /yakuake/sessions addSession > /dev/null
		}

		function yakuake_runcommand() {
			qdbus org.kde.yakuake /yakuake/sessions runCommand "$1" > /dev/null
		}

		function yakuake_settitle() {
			local id="$(qdbus org.kde.yakuake /yakuake/sessions sessionIdList |
				tr , "\n" | sort -g | tail -1 | tr -d '\n')"
			qdbus org.kde.yakuake /yakuake/tabs setTabTitle "$id" "$1"
		}

		function yakuake_showwindow() {
			local wid=$(wmctrl -xl | grep -iF 'yakuake.yakuake' | head -n1 | cut -d' ' -f1)
			if [[ -z "$wid" ]]; then
				qdbus org.kde.yakuake /yakuake/window toggleWindowState > /dev/null
			else
				wmctrl -i -a $wid
			fi
		}

	elif [[ "$comm" == dcop ]]; then

		function yakuake_addsession() {
			dcop yakuake DCOPInterface slotAddSession > /dev/null
		}

		function yakuake_runcommand() {
			dcop yakuake DCOPInterface slotRunCommandInSession "$1" > /dev/null
		}

		function yakuake_settitle() {
			warning "set tab title is not yet supported when using DCOP interface"
		}

		function yakuake_showwindow() {
			ws="$(dcop yakuake 'yakuake-mainwindow#1' visible)"
			if [[ "$?" == 0 && "$ws" == false ]]; then
				dcop yakuake DCOPInterface slotToggleState > /dev/null
			fi
		}

	else
		error_exit 22 "cannot connect to Yakuake"
	fi
}

### Main function

function yakuake_session() {
	local cwd="$PWD"
	local title=''
	local cmd=''
	local hold=0
	local now=1

	# Parse command line options
	local option=''
	local OPTIND=1
	local OPTARG=''

	while getopts ":-:t:p:w:he:q" option; do
		case $option in
			-)
				case "$OPTARG" in
					help)
						show_help
						exit 0
						;;
					homedir)
						cwd="$HOME"
						;;
					workdir)
						cwd="${!OPTIND}"
						[[ "$cwd" == -* ]] &&
							error_exit 1 "missing argument for option '$OPTARG'."
						OPTIND=$(($OPTIND + 1))
						;;
					workdir=*)
						cwd="${OPTARG#*=}"
						;;
					hold|noclose)
						hold=1;
						;;
					*)
						error_exit 1 "unknown option '$OPTARG'."
						;;
				esac
				;;
			p)
				add_profile_setting "$OPTARG"
				;;
			e)
				shift $((OPTIND-2))
				cmd=$(printf '%q ' "$@")
				break
				;;
			t)
				title="$OPTARG"
				;;
			h)
				cwd="$HOME"
				;;
			q)
				now=0
				;;
			\?)
				error_exit 1 "unknown option '$OPTARG'."
				;;
			:)
				error_exit 1 "missing argument for option '$OPTARG'."
				;;
			esac
	done

	if [[ -n "$cwd" && ! -d "$cwd" ]] ; then
		error_exit 2 "working directory does not exist"
	fi

	if [[ -n "$cmd" ]]; then
		if [[ "$hold" == 0 ]]; then
			cmd="exec $cmd"
		fi
	else
		cmd='true'
	fi

	init_ipc_interface

	# Create a new terminal session in Yakuake
	yakuake_addsession > /dev/null ||
		error_exit 4 'cannot create a new session in Yakuake'

	# Setup the session
	SESSION_FILE="$(mktemp --tmpdir "$PROGRAM_NAME-XXXXXXXXXX")"

	cat > "$SESSION_FILE" <<-EOF
		clear
		rm -f '$SESSION_FILE' 2>/dev/null
		$(profile_setup_command)
		if [ -z "\$FISH_VERSION" ]; then
			cd $(printf %q "$cwd") && $cmd
		else
			cd $(printf %q "$cwd"); and $cmd
		fi
	EOF

	# We use souce builtin instead of '.' because of fish shell and
	# we put a space before to exclude it from history.
	yakuake_runcommand " source '$SESSION_FILE'" ||
		error_exit 7 'cannot run a command inside the new session'

	if [[ -n "$title" ]]; then
		yakuake_settitle "$title"
	fi

	# Show the window of Yakuake
	if [[ "$now" == 1 ]]; then
		yakuake_showwindow
	fi
}

# Detect if the script was called with a different user who logged in
logged_user=$(logname)
if [[ "$UID" == 0 && "$logged_user" != "$USER" ]]; then
	su "$logged_user" -c '"$0" "$@"' -- "$0" "$@"
else
	yakuake_session "$@"
fi
